name: mobile_client
description: "ビションとの暮らしを豊かにする情報を共有"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^0.13.1
  flutter_dotenv: ^5.1.0
  minio_new: ^1.0.2
  intl: ^0.18.1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_waji.jpeg"
  adaptive_icon_foreground: "assets/icon_waji.jpeg"
  adaptive_icon_background: "#46B4EB"
